//
// Created by michele on 28/05/19.
//

#ifndef ROS_CUDA_DOOR_RECOGNIZER_CUDA_DOOR_RECOGNIZER_H
#define ROS_CUDA_DOOR_RECOGNIZER_CUDA_DOOR_RECOGNIZER_H

void test_cuda();

#endif //ROS_CUDA_DOOR_RECOGNIZER_CUDA_DOOR_RECOGNIZER_H
